name: Notebook UX Review

on:
  pull_request:
    paths:
      - '**.ipynb'
  push:
    paths:
      - '**.ipynb'

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # Add this line to grant write permissions to pull requests
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run notebook review for all .ipynb files
        run: |
          npm install
          for nb in $(find . -name '*.ipynb'); do
            echo "## Review for $nb" >> review-summary.md
            node review-notebook.js "$nb" >> review-summary.md
            echo "" >> review-summary.md
          done

      - name: Upload review summary
        uses: actions/upload-artifact@v4
        with:
          name: notebook-review-summary
          path: review-summary.md

      - name: Add review summary to PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const summary = fs.readFileSync('review-summary.md', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });